// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0Kl_uPWrfwXxc7knEf5NMLyC1pgkBMjE',
    appId: '1:767328913445:web:3658c82e538385db2a57cc',
    messagingSenderId: '767328913445',
    projectId: 'otis-76de9',
    authDomain: 'otis-76de9.firebaseapp.com',
    storageBucket: 'otis-76de9.appspot.com',
    measurementId: 'G-15ZDGXNZ1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3zZcPP1OJyGSCk-zPXVTRRWA5ji3kMzk',
    appId: '1:767328913445:android:ee20780e7e5dfcbb2a57cc',
    messagingSenderId: '767328913445',
    projectId: 'otis-76de9',
    storageBucket: 'otis-76de9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALBlLRgwRebAMoPAq4Fuh-4nhRsjdVGaY',
    appId: '1:767328913445:ios:4655ded141fe4ea62a57cc',
    messagingSenderId: '767328913445',
    projectId: 'otis-76de9',
    storageBucket: 'otis-76de9.appspot.com',
    iosClientId: '767328913445-ppqlue9kcfhn82o2lkppj5u380tc4aes.apps.googleusercontent.com',
    iosBundleId: 'ch.enyo.otis',
  );
}
